name: Pack

on:
  push:
    branches:
      - main

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: npm ci

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-latest
          path: vscord-*.vsix